language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
deploy:
  provider: surge
  project: ./dist/
  skip_cleanup: true
  domain: gestantesxcoronavirus.surge.sh
  on:
    branch: master

